# Staging environment configuration
sync:
  include:
    - src/**
  exclude:
    - "*.pyc"
    - "__pycache__"
ECHO is on.
artifacts:
  wheels: []
ECHO is on.
run_as:
  user_name: "your-service-principal@your-domain.com"
