name: Banking Data ETL Pipeline

# Trigger on push to the main branch or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

# Set concurrency to avoid simultaneous runs
concurrency: prod_environment

# Permissions for GitHub Actions
permissions:
  contents: read

jobs:
  run-etl:
    runs-on: ubuntu-latest
    name: Trigger Databricks ETL
    environment: Prod
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      # Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Databricks CLI
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      # Update Databricks Git Folder
      - name: Update Databricks Git Folder
        run: |
          databricks repos update /Repos/samanarika52@outlook.com/banking_data_repo_ram --branch main
        if: env.DATABRICKS_TOKEN != ''

      # Trigger Databricks job
      - name: Run Databricks ETL Job
        run: |
          databricks jobs run-now --job-id 911328418800320
        if: env.DATABRICKS_TOKEN != ''